Story1
danicatt/danicatt.github.io pull request #7
Opened 2020-03-04 15:47 UTC by danicatt

As ready as I can be!

2020-03-04 15:58 UTC, mporam requested changes
difficulty pressing the nav links on mobile, consider spacing it out from the social icons

the about me pic isnt centralised

projects are not centralised on mobile

project images are not circles

2020-03-05 09:08 UTC, danicatt commented
Made changes requested by Mike.

2020-03-05 09:19 UTC, soneillcode requested changes

2020-03-05 09:19 UTC, soneillcode commented on index.html
> +
Worth sorting out textmate for indentation and spacing

2020-03-05 09:19 UTC, soneillcode commented on index.html
> +</html>
This is missing a new line at the end of the file. It's sounds odd but it's important that all files have a new line at the end

2020-03-05 09:23 UTC, danicatt commented on index.html
> +
Fixed indentation on CSS and html with tabstospaces.com

2020-03-05 10:14 UTC, danicatt commented on index.html
> +</html>
Added a new line.

2020-03-05 10:42 UTC, closed without merging